### ISSUE TITLE
OSX error: General viewer is not available!

### ISSUE THREAD

**Issue by kiryph** [lervag/vim-latex#100]
I am getting following error on Mac OSX 10.9:
```
Error detected while processing function latex#init..latex#view#init..<SNR>29_check_method_general:
line    2:
General viewer is not available!
line    3:
g:latex_view_general_viewer = xdg-open
```

On all Mac OSX the general viewer is called 'open' not 'xdg-open' and always available without installation of anything.

Can you adjust your code if has('macunix') to set the general viewer just to 'open'?

**Comment by lervag** [comment]
Before I do anything, the issue is solved if you add the following to your vimrc file:
```
let g:latex_view_general_viewer = 'open'
```

I'll keep the issue open as I agree that I should add default value based on OS if possible.

**Comment by kiryph** [comment]
Thanks for your quick response. Adding as a default would really be great.
I try to keep my vimrc short. So I always appreciate sensible default configurations of plugins.

**Comment by lervag** [comment]
I realized this was too easy to not do straight away. I think the latest patch should fix the problem.

**Comment by kiryph** [comment]
I can confirm that the error has disappeared. As far as I can see the plugin works now without any configuration on my mac. Thank you very much.

**Comment by lervag** [comment]
No problem :-)

søn. 18. jan. 2015, 23.06 skrev kiryph <notifications@github.com>:
