### ISSUE TITLE
<plug> mappings

### ISSUE THREAD

**Issue by Konfekt** [lervag/vim-latex#103]
How about providing all normal mode editing mappings as `<plug>(vim-latex)` mappings? 

For example, `dse` would be mapped to `<plug>(vim-latex-dse)`. 

The advantage would be set they can be made repeatable by the repeat.vim plugin out of the box, for example by
```
nnoremap <plug>(vim-latex-dse) :call latex#change#env('')<cr>\|silent! call repeat#set('<plug>(vim-latex-dse)',v:count)<CR>
```

**Comment by lervag** [comment]
I was actually thinking about this recently. I didn't know about the repeat possibility, which I really like.

I've also realized that I think I like better to organize all mappings in the same place. I am not sure about this though. I was thinking to perhaps make a "module" like `autoload/latex/mappings.vim`, or even `autoload/latex/interface.vim`. The latter could also include commands. Do you have any thoughts on this yourself?

**Comment by Konfekt** [comment]
The naming `mappings` makes it easier to locate them when looking at the source. 

So perhaps `commands` and `mappings` better than mingling them into a single `interface` file, rather in a folder of the same name.

That said, my philosophy is that the commands such as starting compilation, displaying errors are best handled by the command line but those editing text deserve mappings. Though every map should be a `<plug>map`.

**Comment by lervag** [comment]
I am not sure I understood your philosophy: Did you mean you don't want functionality in vim to start compilation, but that you rather do that separately in the command line? In that case, I partly agree that this is a sane philosophy, but personally I really enjoy the simplicity of controlling the compilation and displaying errors inside vim.

Anyways, I think the following mapping-scheme makes sense:
1. Each "module" file defines their own `<plug>...` mappings much like the mappings are defined today.
2.. I'll keep command definitions the way it is today.
3. The mapping of `<plug>...` expressions is then done in a new `mappings.vim` file, which will allow to wrap over `repeat.vim`.

Do you agree?

**Comment by Konfekt** [comment]
> Anyways, I think the following mapping-scheme makes sense:
> 1. Each "module" file defines their own <plug>... mappings much like the mappings are defined today.
> 2.. I'll keep command definitions the way it is today.
> 3. The mapping of <plug>... expressions is then done in a new mappings.vim file, which will allow to > wrap over repeat.vim.

Sounds good. By modules you mean the files found in

https://github.com/lervag/vim-latex/tree/master/autoload/latex ?

> I am not sure I understood your philosophy: Did you mean you don't want functionality in vim to start compilation, but that you rather do that separately in the command line?

Yes, I reverted to Command Line abbreviations to start compilation (toggle, singleshot) but realized that I use mappings for forward and reverse search. So at the end its perhaps only a question of frequency. Using default mappings for text editing functions but commands for those controlling latexmk would be a good compromise but no strong opinionss on it. The way it is is just fine but know that additional `<plug>` mappings are coming, this questioin resurged.

**Comment by lervag** [comment]
Yes, in lack of a better word I call the files in `autoload/latex` modules.

**Comment by lervag** [comment]
I've just pushed an updated to use `<plug>` for all mappings (https://github.com/lervag/vim-latex/commit/864f4d3a2d2911b6b145e7b66cd8e3b51a49aa31). The repeat functionality is not added yet.

**Comment by lervag** [comment]
I think this solves the issue as well, or did the issue also include the repeat coupling?

**Comment by Konfekt** [comment]
Hmm.. I started the issue with the idea that the `<plug>` mappings include the `!silent repeat...` appendix so that the vim-latex user get the repeatability for free if he uses those.

On a sidenote, I think at some points the mappings in mappings.vim are off by one, see
```
+ nnoremap <buffer> dse <plug>VimLatexDeleteEnv
+ nnoremap <buffer> cse <plug>VimLatexDeleteCmd
+ nnoremap <buffer> dsc <plug>VimLatexChangeEnv
```

**Comment by Konfekt** [comment]
Repeatiability is just a matter of appending
```
\|silent! call repeat#set('<plug>MAPPING',v:count)<CR>
```
to all <plug>MAPPING.

**Comment by lervag** [comment]
Thanks, I fixed the bug.

I'll add the repeat later today or this weekend.

**Comment by Konfekt** [comment]
You could try something like
```
  redir => mappings
    silent! smap
  redir END

  " List of all printable characters. See
  " NEOSNIPPET: /autoload/neosnippet/mappings.vim
  for MAP in map(filter(split(mappings, '\n'),
        \ "v:val !~# '^s' && v:val !~ '^\\a*\\s*<plug>VimLatex'"),
        \ "matchstr(v:val, '^\\a*\\s*\\zs\\S\\+')")
   execute nmap `<plug>repeatableMAP MAP:silent! call repeat#set('<plug>MAP',v:count)<CR> 
  endfor
endfunction
```

**Comment by lervag** [comment]
Interesting. I'm curious, perhaps it is better to just manually bookkeep which of the mappings require a repeatable mapping?

And is there any reason to create two versions of each repeatable map?

**Comment by Konfekt** [comment]
Yep. Probably it's saner to just bookkeep. I only added it in there to avoid making the command invalid by recursion. 

Correclty, it should be
```
nnoremap <script> <SID>repeat :silent! call repeat#set('<plug>MAP',v:count)<CR>
nmap <plug>repMAP <plug>MAP<SID>repeat
```

**Comment by lervag** [comment]
OK, I might be stupid here, but I'm not getting how to do this properly. Could you either write out a full example, or perhaps open a pull request?

**Comment by lervag** [comment]
To be more specific: Your example based on neosnippet does not work. I've fixed a couple of minor bugs, but still... and I don't understand how the last example should be. For instance, in `<plug>repMAP`, is `MAP` supposed to be understood as any of my mappings, or is it a variable as in the above for loop, or what?

**Comment by Konfekt** [comment]
Well, first bookkeeping is the better solution than the neosnippet script that I thought could somehow be of help if all mappings starting with `<plug>VimLatexChange` for example are to be made repeatable.

In conjunction, the now obsolete idea amounted to
```
  redir => mappings
    silent! smap
  redir END

  for MAP in map

   execute 'nnoremap <script> <SID> '.MAP.'repeat ':silent! call repeat#set("<plug>'.MAP",v:count)<CR>'
   execute 'nmap <plug>'.MAP.'Repeatable'.' <plug>'.MAP'.'<SID>'.MAP.'repeat' 
  endfor
```

Here `map` is supposed to be a list of appendixes `VimLatex..` following `<plug>`.

**Comment by lervag** [comment]
Ok, so now I've added the following to change.vim:

```vimL
  " Create repeatable mappings
  let s:repeatable_mappings = [
        \ 'VimLatexDeleteEnv',
        \ 'VimLatexDeleteCmd',
        \ 'VimLatexChangeEnv',
        \ 'VimLatexChangeCmd',
        \ 'VimLatexToggleEnvStar',
        \ 'VimLatexToggleDelim',
        \ ]
  for MAP in s:repeatable_mappings
    execute 'nmap <plug>' . MAP . 'Repeat' . ' <plug>' . MAP
          \. ':silent! call repeat#set(''\<plug>' . MAP . ''', v:count)<cr>'
  endfor
```
I think these are the only mappings that (at the moment) should be repeatable. The mappings are created, but it doesn't work. :\

**Comment by Konfekt** [comment]
Hmmm.. first off better use the script map workaround 
```
execute 'nnoremap <script> <SID>'.MAP.'repeat ':silent! call repeat#set("<plug>'.MAP.'",v:count)<CR>'
```
because something in 
```
:silent! call repeat#set(''\<plug>' . MAP . ''', v:count)<cr>
```
could be remapped.

**Comment by lervag** [comment]
I managed to make it work, although you are right, something gets remapped.

**Comment by Konfekt** [comment]
For example, I swapped `:` and `,`.

**Comment by Konfekt** [comment]
Ok. Suggestion
```
execute  'nnoremap <script> <SID>'.MAP.'Repeat ':silent! call repeat#set("<plug>'.MAP.'",v:count)<CR>'
 execute 'nmap <plug>' . MAP . 'Repeat' . ' <plug>' . MAP
          \. '<SID>MapRepeat'
```

**Comment by lervag** [comment]
I found a slightly different way to do this where instead I call the `repeat#set` function at the end of my own functions. This seems to work very well here, at least.
