### ISSUE TITLE
<F5> Mapping?

### ISSUE THREAD

**Issue by DavidRdgz** [lervag/vim-latex#104]
I'm on a mac 

```bash
ProductName:	Mac OS X
ProductVersion:	10.10.1
```

running vim

```bash
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 25 2014 22:14:21)
MacOS X (unix) version
Included patches: 1-488
Compiled by Homebrew
```

Using the vundle plugin I do not get a keymap for F5. Running :imap I get the following,

```bash
i  <F7>        *@<C-R>=latex#change#to_command()<CR>
i  ]]          *@<C-R>=latex#change#close_environment()<CR>
!  <D-v>         <C-R>*
```

What's wrong?

**Comment by lervag** [comment]
I must admit I do not understand what you mean. `vim-latex` does not provide any mapping for `<F5>`. Perhaps you mistake this plugin for [LaTeX-Suite](http://vim-latex.sourceforge.net/), which is also known as vim-latex?

**Comment by DavidRdgz** [comment]
I am really sorry about the confusion. I did not notice that they were named the same. I really appreciate your help.

**Comment by lervag** [comment]
No problem!
