### ISSUE TITLE
Not compiling on Windows with `shellslash`

### ISSUE THREAD

**Issue by salviati6** [lervag/vim-latex#105]
Environment: Windows 7 SP1 64-bit, VIM 7.4.589 64-bit
Symptom: On Windows with `shellslash` set, compiling with vim-latex (`\lv`) reports success but nothing is actually done.

This is much like Issue #40, unfortunately the fix to that issue does not seem to work on this one.

From `:h shellescape()`:

> On MS-Windows and MS-DOS, when 'shellslash' is NOT set, it will enclose {string} in double quotes and double all double quotes within {string}.

On Windows with `shellslash` set, `shellescape()` will enclose its returned string in single quotes to produce a `cmd` like

> cmd /s /c "cd /D 'C:\PATH' ...

which cannot be recognized by `cmd` and consequent operations are automatically aborted (the compilation never actually starts in this case).

Maybe a change to `autoload\latex\latexmk.vim:89` is necessary, or just inform Windows users to turn off shellslash in the docs. However, some plugins (e.g., `vim-startify`) are not functioning without `shellslash`.

**Comment by lervag** [comment]
Interesting. As I think I mention in the docs, I am not a windows user myself and I therefore rely on windows users to help me fix problems such as these.

Do I understand correctly that the issue may be "fixed" by turning of `shellslash`? One possibility would then be to turn off shellslash temporarily in the functions where necessary. However, I am not really sure I want that, because I want the code to be as clean as possible.

**Comment by salviati6** [comment]
Thanks for the prompt reply!

I work cross-platform on OS X and Windows, and I wish to keep `shellslash` on Windows because it gives me a consistent environment (always forward slashes in paths). I totally agree with the idea to keep the code succinct, and I think only minor changes are necessary. I'm new to VIM and I'll try to fix the problem.

**Comment by lervag** [comment]
I understand. I will be very happy to consider pull requests!

Let me know if I can assist somehow. A couple of tips: I've created some utility functions that are mapped to `<localleader>li` and `<localleader>lo` that may be helpful in debugging. The first shows the important information that is stored by vim-latex, and the latter shows that output from the `latexmk` command itself.

**Comment by salviati6** [comment]
The helper functions are extremely useful! I like the way this plugin is designed, and I'm currently working on my LaTeX docs solely with it.

I am looking into the code and I believe a small hack to `shellescape()` will be enough. I don't want to alter `shellslash` even temporarily because it's global any may affect other plugins.

**Comment by lervag** [comment]
Thanks! I'm happy you like it. Please feel free to suggest bug fixes, improvements and ideas for new features. As mentioned, I want to keep things relatively simple, but I will definately want to add useful features.
