### ISSUE TITLE
New mappings are slow

### ISSUE THREAD

**Issue by lervag** [lervag/vim-latex#109]
After implementing mappings that use `<plug>`, the mappings are suddenly much slower than earlier. For instance, when default mappings are enabled, typing `dsc` to remove the surrounding command takes about a second before it is completed.

@Konfekt Do you have any idea what might be causing this?

**Comment by Konfekt** [comment]
Perhaps a timeout problem. Vim is waiting for the key sequence to be possibly completed to another mapping.

For example
```
nnoremap q :echo 'q'<cr>
nnoremap qq :echo 'qq'<cr>
```
leaves Vim hanging for a second after hitting `q`.

**Comment by Konfekt** [comment]
Ah, solved it.

Since you did not parenthesize the maps, Vim is wondering if for example `<plug>VimLatexDeleteCmd` extends to `<plug>VimLatexDeleteCmdRepeat`!

**Comment by lervag** [comment]
Yes, I think you're right. Although it will lead to even longer names, it seems `<plug>(vim-latex-...)` is a better naming convention. I could save some space by using `<plug>(vl-...)`.
