### ISSUE TITLE
latex#complete#labels() is not robust against spaces in file path

### ISSUE THREAD

**Issue by danielwe** [lervag/vim-latex#110]
I had this problem where I could only get citation completions to work for a particular document, and never label completions. Renaming folders such that the path to the document became free of spaces fixed the problem. Thus, it seems like latex#complete#labels() breaks when there are spaces in the file path.

**Comment by lervag** [comment]
Hi! I was able to reproduce the issue and I think I've solved it. At least it worked for my simple example (see `test/comletion`).
