### ISSUE TITLE
Strange identation with multi-line formulas delimited by \[ \] 

### ISSUE THREAD

**Issue by Rmano** [lervag/vim-latex#112]
Hi --- I was writing a document similar to this 

```
\documentclass{standalone}
\begin{document}
\begin{quotation}
    Text text text 
    \[ f = long equation 
        \]
    text text text
    \[ g = another long equation 
        \]

    text text text 
\end{quotation}
\end{document}
```

and then, while in the middle of the thing, I tried to reindent the whole `quotation` environement --- select all of it with `vae` and then `=`. Surprisingly I got: 

```
\documentclass{standalone}
\begin{document}
\begin{quotation}
    Text text text 
    \[ f = long equation 
        \]
        text text text
        \[ g = another long equation 
            \]

            text text text 
        \end{quotation}
\end{document}
```

...is this normal? IS there something strange going in with `\[` and `\]`? 

Thanks,
Romano

**Comment by lervag** [comment]
That is strange. When I do the same thing I get:
```tex
\begin{quotation}
  Text text text 
  \[ f = long equation 
  \]
  text text text
  \[ g = another long equation 
  \]

  text text text 
\end{quotation}
```

Could you try agin with a minimal vimrc file?

**Comment by Rmano** [comment]
I tried with in .vimrc: 

```
" vundle setup, must tay at top
set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
"Plugin 'LaTeX-Box-Team/LaTeX-Box'
Plugin 'lervag/vim-latex' 
"
"All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
```

But I still have the same result. Puzzling.

**Comment by lervag** [comment]
Could you try instead (although I don't think this should solve anything):
```vimL
set nocompatible
let &rtp = '~/.vim/bundle/vim-latex,' . &rtp
filetype plugin indent on
syntax enable
```

Also, what version of vim are you using, and on which OS?

**Comment by Rmano** [comment]
Ok, with your snippet in `.vimrc` identation works. Now I will have to chase down where it is messed up... probably some remnant of LaTeX-Suite or LaTeX-box...

**Comment by lervag** [comment]
Strange, yes. I almost suspect it to be due to Vundle. It does not look like you loaded LaTeX-Box or LaTeX-Suite...

In any case, I don't think this is due to vim-latex, so I'll close the issue. Let me know if there is anything I can do to help you find the problem.

**Comment by lervag** [comment]
Btw, perhaps you could try https://github.com/junegunn/vim-plug instead?

**Comment by Rmano** [comment]
Hmmm... seems nice --- let me dig out how to get rid of vundle. ;-)

**Comment by lervag** [comment]
Feel free to look at my `vimrc` file:
https://github.com/lervag/dotvim/blob/master/vimrc

**Comment by Rmano** [comment]
> Feel free to look at my vimrc file:
> https://github.com/lervag/dotvim/blob/master/vimrc

What is the emoticon for yaw dropping one the table with a a sound "clonk" ? ;-)
Thanks a lot. I will study it... I'll really need a bit of time.

**Comment by lervag** [comment]
Hehe, yeah, I guess it has grown rather large over time... :p

**Comment by Rmano** [comment]
OK --- I switched form Vundle to vim-plug by junegunn and all is ok now. Strange strange strange. Thanks a lot!

**Comment by lervag** [comment]
No problem. Glad it works now.
