### ISSUE TITLE
make operator mappings more stable

### ISSUE THREAD

**Issue by Konfekt** [lervag/vim-latex#113]
The use of `normal v` in the operator mappings such as
```
onoremap <silent><buffer> ie :normal vie<cr>
```
will lead to errors if the user remaps `v` in normal mode. With
```
nnoremap <script><buffer> <SID>v v
onoremap <silent><buffer> ie :execute "normal \<SID>vie"<cr>
```
instead, the opertor map remains intact.

**Comment by Konfekt** [comment]
Found on http://stackoverflow.com/questions/8862290/vims-plug-based-mappings-dont-work-with-normal-command

**Comment by lervag** [comment]
Interesting problem, and very good that you found the solution.

**Comment by Rmano** [comment]
Hi --- I am not an expert here but I am puzzled by a little thing --- I am reading  [learning vimscript the hard way](http://learnvimscriptthehardway.stevelosh.com/chapters/29.html) and the author says: 

> When writing Vim scripts you should always use `normal!`, and never use plain old `normal`.
> You can't  trust what keys your users will have mapped in their ~/.vimrc files.

Isn't this one related? Or I have to study more?

**Comment by Konfekt** [comment]
It is the same issue. However, now that we now what every remaped map does (before `v` was up to the user's `.vimrc`), `normal` is fine.

**Comment by lervag** [comment]
@Rmano Yes, it is related,  but not directly relevant: The `<plug>` mappings actually requires the recursive variant of the mappings in order to work, but since a `<plug>` key sequence is guaranteed to be unique, it is also safe.
