### ISSUE TITLE
compiler plugin

### ISSUE THREAD

**Issue by Konfekt** [lervag/vim-latex#114]
How about a compiler file `latexmk` for vim-latex that sets &errorformat  (as I think `&mkrpg` is not used) ?
 
See http://vim.wikia.com/wiki/Errorformat_and_makeprg

For example, I got curious upon reading

https://gist.github.com/ajh17/a8f5f194079818b99199

and tried this with syntax checking with `lacheck`. As there may be many build programs for a FileType (build, compile and lint) , you keep track of these by a compiler file, say `~/.vim/compiler/latexmk.vim`. 

For example, that of `lacheck` would look like 
```
if exists("current_compiler")
  finish
endif

let current_compiler = "lacheck"

CompilerSet errorformat="%f",\ line\ %l:\ %m
CompilerSet makeprg=lacheck
```
and then you can switch between these by `compiler lacheck` or `compiler latexmk`.

**Comment by lervag** [comment]
This is interesting, I agree. Both the tip about `lacheck`, and on the compiler functionality.

You are correct that `&mkprg` is not used. Your idea would require the following changes, I think:
1. Create `compiler/latexmk.vim` and move errorformat definitions from `autoload/latex.vim` to the new file.
2. Run `compiler latexmk` during initialization of `vim-latex`.
3. Add compiler `lacheck` according to your example.

After these changes, I could also add a command that runs `lacheck` by temporarily changing the compiler. This could then be mapped in a similar way as other functionalities.

**Comment by Konfekt** [comment]
Impeccable. Full agreement with every single step.

**Comment by Konfekt** [comment]
The command could look like
```
command! -buffer Lmake silent lmake % | lwindow | silent redraw! | wincmd p
command! -buffer Lmak  Lmake
```
and optionally:
```
autocmd! BufWritePost <buffer> noautocmd Lmake
```
This is inspired by https://github.com/romainl/dotvim/blob/c0dd086936b1d42894db57bf1c8d95f4c5baf0ae/bundle/lang-javascript/after/ftplugin/javascript.vim#L43

**Comment by lervag** [comment]
One thing: You are inconsistently mixing `lmake` and `Lmake`. I suspect you are using `vim-dispatch` by Tim Pope? In any case, I think the first three changes mentioned should be compatible with such other plugins, but the latter change where I add commands to run `lacheck` should not depend on any other plugins, and will therefore use the lower case variants `lmake` og `make`.

**Comment by Konfekt** [comment]
Oh, ok. I didn't know that there is already an official version of Lmake by vim-dispatch. I never used it. 

It was just the, too self-suggesting, command name I came up with. Perhaps `LmakeOutput` instead.

**Comment by lervag** [comment]
How about `VimLatexCheck`? I want to use consistent command names...

**Comment by lervag** [comment]
Or `VimLatexLacheck`.

**Comment by lervag** [comment]
I've begun the work now. I've pushed two commits that should finish my above mentioned tasks 1 through 3. It remains to create the command that runs `lacheck`.

However, one thing: When I run `make` with compiler `lacheck`, I get a lot of annoying output. I guess I should run `silent make`, or is there a better way to remove the noise?

**Comment by Konfekt** [comment]
Yeah, that's fine as well. `Lmake` was meant as a general template under the hood, perhaps for myself after all. My suggestion was `Lacheck` but of course `VimLatexCheck` is what it should be called in `vim-latex`.

**Comment by Konfekt** [comment]
By the way: https://github.com/tpope/vim-dispatch/issues/31

**Comment by lervag** [comment]
Latest push should solve this issue by adding the commands `VimLatexLacheck`. Please test and comment.

**Comment by Konfekt** [comment]
Two thumbs up :+1:  :+1: , works perfectly. 

How about `there is a syntax checker` instead of `there does exist syntax checker` at https://github.com/lervag/vim-latex/commit/7e5a465f3bdc8a58682c1859fe07d5efd413acd1#diff-10fbde5f0b5f29974b83387f709ae263R799?

**Comment by lervag** [comment]
Thanks! I updated the paragraph.
