### ISSUE TITLE
Synctex forward-search: configuration for qpdfview?

### ISSUE THREAD

**Issue by lahwaacz** [lervag/vim-latex#122]
[qpdfview](http://launchpad.net/qpdfview) uses the following syntax for synctex navigation:

    qpdfview --unique foobar.pdf#src:foobar.tex:42:0

This is quite similar to how okular works, but not the same - the order of parameters is different and it also takes the column number, which is not passed to okular.

Is there any chance that this could be configured via some wildcards that would be replaced with the relevant information or are separate functions for each viewer necessary?

**Comment by lervag** [comment]
I'm sorry, but for forward search with synctex I had to add a new function for `qpdfview`. However, this is/was very simple, and is already done. If you use `let g:latex_view_method = "qpdfview"`, you should now be able to open the viewer with `\lv`, which will also do forward search when the viewer is already opened.

I see now that I perhaps should have implemented this in a different way by using a general function with wildcards. But the way it is implemented now is very explicit and clear (IMHO), and although it does not make it easy to add new viewers with forward search directly through options, it does make it easy to add a new viewer by adding some new functions.

**Comment by lahwaacz** [comment]
Thanks for the quick fix. In the end I guess it depends on how many viewers use the command-line approach and how many require some special attention.

**Comment by nasenatmer** [comment]
Haha, [first adopter](https://wiki.archlinux.org/index.php/User_talk:Jakobh) of today's [pr campaign](https://wiki.archlinux.org/index.php?title=LaTeX&diff=prev&oldid=362548) already active in the issue tracker! welcome @lahwaacz!

**Comment by lervag** [comment]
@nasenatmer Thanks for mentioning my plugin on Arch's wiki!

@lahwaacz No problem. I'm working on a major improvement of the view functionality codebase now. Should be ready pretty soon. It will still be based on functions for the different viewers, but in a much more general way.
