### ISSUE TITLE
Error: Key not present in Dictionary: init

### ISSUE THREAD

**Issue by xu-cheng** [lervag/vim-latex#124]
After update vim-latex, I get the following error every time I open a tex file:

```
Error detected while processing function latex#init..latex#view#init:
line   29:
E716: Key not present in Dictionary: init
Press ENTER or type command to continue
```

My vim config: https://github.com/xu-cheng/dotfiles/tree/master/nvim
Related to vim-latex: https://github.com/xu-cheng/dotfiles/blob/master/nvim/pluginrc.d/vim-latex.vim

**Comment by lervag** [comment]
Should be fixed in https://github.com/lervag/vim-latex/commit/deb80daa4e25b308d33d74e44cf22e7d5c7da9f7.

**Comment by xu-cheng** [comment]
Thanks, it's fixed.
