### ISSUE TITLE
additions to `c\dsc` and `c\dse`

### ISSUE THREAD

**Issue by Konfekt** [lervag/vim-latex#126]
If the user has `vim-surround` installed, how about adding (perhaps only in the documentation) something like
```vim
augroup latexSurround
   autocmd!
   autocmd FileType tex call s:latexSurround()
augroup END

function! s:latexSurround()
   let b:surround_{char2nr("e")} = "\\begin{\1environment: \1}\n\t\r\n\\end{\1\1}"
   let b:surround_{char2nr("c")} = "\\\1command: \1{\r}"
endfunction
```
so that there is a corresponding `ysc` and `yse` command? Note that `yse` is somewhat superfluous because there is (experimentally) already `ysl` in `vim-surround` by default.

**Comment by lervag** [comment]
Could you explain what this does? Does it only provide `ysc` and `yse`, or does it provide any of the other `vim-surround` functionalitites as well?

**Comment by Konfekt** [comment]
Not much more than that. Of course, also `Se/c` in visual mode `yss/Se/c` and the likes. But nothing like `dsc/e` or `csc/e` because you can't customize targets: https://github.com/tpope/vim-surround/issues/130
