### ISSUE TITLE
mupdf -> vim search

### ISSUE THREAD

**Issue by Konfekt** [lervag/vim-latex#89]
Does `g:latex_viewer=mupdf` enable inverse search, from mupdf to vim?

If not, maybe there's a chance to implement the code in https://github.com/ying17zi/vim-live-latex-preview into vim-latex? (See also http://webcache.googleusercontent.com/search?q=cache:KTm5KoCvlqgJ:jlebl.wordpress.com/2011/01/13/vim-evince-and-forward-and-backward-latex-synctex-search/+&cd=1&hl=fr&ct=clnk&gl=de)

How would that be implemented? Under SumatraPDF, it is by doubleclicking.

**Comment by lervag** [comment]
No, sorry, `g:latex_viewer=mupdf` only enables forward search from vim to mupdf.

I don't really see that your suggested link provides inverse search with mupdf, but then I might not quite understand how it works... for forward search, I am using the same basic idea with synctex and xdotools.

As for your second link, I don't really see how it relates, as it is not about mupdf at all, but rather about evince.

One possibility for inverse search with mupdf is to read the title line of the document and fetch the page number, which may be inversely search with synctex to find the corresponding editor line of the first line on that page. However, I think inverse search is only interesting if it really works fully, and so I am not interested in implementing this hack.

**Comment by Konfekt** [comment]
Happy new Year!

The below function, invoked in Vim, by a binding such as `<leader>lr`, jumps to a position of the  currently viewed page in mupdf, as you explain in your last paragraph. 

This is best possible if inverse search has to be invoked from Vim. 

I find it easier to find one's way around in the PDF rather than TeX file. So I'd be happy to propose a pulll request that adds this function as `latex#view#inverse()` or another sensible name to vim-latex.

```
function! MuPDFReverse()
lcd %:p:h
if b:Pdfviewing == "yes"
let activepage = 0
let activepage = system("xdotool getwindowname " . b:MuPDFWindowID . " | sed 's:.* - \\([0-9]*\\)/.*:\\1:' | tr -d '\n'")
if activepage > 0
let inputfile = system("synctex edit -o \"" . activepage . ":288:108:" . b:Pdfroot . ".pdf\" | grep 'Input:' | sed 's/Input://' | head -n1 | tr -d '\n' 2>/dev/null")
if inputfile =~ expand("%")
let gotoline = 0
let gotoline = system("synctex edit -o \"" . activepage . ":288:108:" . b:Pdfroot . ".pdf\" | grep -m1 'Line:' | sed 's/Line://' | head -n1 | tr -d '\n'")
if gotoline > 0
exec ":" . gotoline
echo "Went to line " . gotoline
endif
else
echo "Synctex reported an external location - " . inputfile
endif
else
echo "Cannot read MuPDF page number."
endif
endif
endfunction 
```
It seems not to use any additional scripts. The buffer variables such as `b:MuPDFWindowID` and `b:PDFRoot` are also known in vim-latex under different naming (and, if suitable, a corresponding command and mapping).

**Comment by lervag** [comment]
Happy new year to yourself! :)

I think my last commit should implement this as desired. Please test, it works as I expected here.

**Comment by Konfekt** [comment]
Thanks! It is on purpose, but it would be much more convenient if instead of
```
if mupdf_infile !~ expand("%") | return | endif
```
simply
```
  execute 'edit '.mupf_infile
```
This way, reverse search also works if the currently viewed page in the Pdf viewer leaves the currently edited buffer in Vim.

**Comment by lervag** [comment]
Good point! I'll make the change immediately.

**Comment by lervag** [comment]
Fixed in f3be519af1f5820bbdb250ae761fbb439b2f1e8d.

**Comment by Konfekt** [comment]
Thanks! I was just about to make a pull request as it works just fine over here.

**Comment by lervag** [comment]
No problem! :) I'm happy I implemented this, as I realize I might use it myself (even though I thought I wouldn't).

Let me know if you have other ideas/suggestions.

**Comment by Konfekt** [comment]
Well, at some point one might think about evaluating the mouse cursor position to jump to the exact line it is point at..

**Comment by lervag** [comment]
Hehe, yes, that would be nice. I'll be glad to accept a pull request!

**Comment by Konfekt** [comment]
Ok, I will think about it. This sounds really useful, because in Linux the focus is where the mouse pointer is at. So you can scroll in the pdf document by your mouse and keep editing in Vim.

**Comment by Konfekt** [comment]
Well perhaps this is even possible.
```
xdotool getwindowname 50331739
```
gives
```
document.pdf - 4/34 (96 dpi)
```
and
```
xdotool getmouselocation --shell
```
gives
```
X=267              
Y=124
SCREEN=0
WINDOW=45580382
```
Therefore, now that we save MuPdf's Window ID we only have to translate Pixels into dpi.

**Comment by Konfekt** [comment]
Well perhaps this is even possible.
```
xdotool getwindowname 50331739
```
gives
```
document.pdf - 4/34 (96 dpi)
```
and
```
xdotool getmouselocation --shell
```
gives
```
X=267              
Y=124
SCREEN=0
WINDOW=45580382
```
Therefore, now that we save MuPdf's Window ID we only have to translate Pixels into dpi.

**Comment by lervag** [comment]
Yes, however, you also need to find the position of the original window as well. This is unfortunately not on my priority list right now, and since the main functionality is already working I think I'll leave this for you (or others) for now. If you find a nice way to do the maths and implementation, then I'll be happy to merge a pull request or assist in deciding how to best add the functionality.

**Comment by Konfekt** [comment]
Yes, two problems remain:

* the coordinates are not relative to the mupdf window
* the document area visible in the mupdf window is unknown.

Perhaps better to shift attention to implementing this in mupdf itself.

**Comment by lervag** [comment]
Yes, I agree: This should be implemented in mupdf itself. The main developers won't do it themselves, but they will consider merging patches if anyone would be willing to make one. :\

**Comment by Konfekt** [comment]
By the way, the lines
```
$compiling_cmd = "xdotool search --name \"%D\" " .
                 "set_window --name \"%D compiling...\"";
$success_cmd = "xdotool search --name \"%D\" " .
               "set_window --name \"%D OK\"; " .
               "gvim --remote-expr 'latex#latexmk#errors(0)'";
$failure_cmd = "xdotool search --name \"%D\" " .
               "set_window --name \"%D FAILURE\"; " .
               "gvim --remote-expr 'latex#latexmk#errors(0)'";
```
in .latexmkrc break inverse search because they kill the current page title in mupdf. Perhaps that should go into the doc.

**Comment by Konfekt** [comment]
They should also better be setup in `g:latex_latexmk_options` so that server instance and `vim` or `gvim` are used, depending on `if('has_guirunning')`.

**Comment by lervag** [comment]
Regarding the page number: Perhaps there is another way to read the page number? I think there is, I think I took a shortcut, actually. Will look into it.

For the last comment: I'm not really sure what you mean by "They". In your example you're using the error callbacks, which are already implemented. I guess you mean the callbacks to change window titles?

In any case, I guess it sort of does make sense to at least partly get rid of the latexmkrc file. It seems that we're heading that way, at least. I'll think about it. But my first thought is that the main problem may be solved by an update to the reverse search method.

**Comment by lervag** [comment]
Btw: I'd appreciate if we could continue this discussion in the new issue #96.
