### ISSUE TITLE
Mupdf inverse search only works when page number is in title string

### ISSUE THREAD

**Issue by lervag** [lervag/vim-latex#96]
See [#89](https://github.com/lervag/vim-latex/issues/89#issuecomment-69758005).

**Comment by Konfekt** [comment]
Yep, I meant those latexmkrc lines that change the Window title of mupdf according tobthe compile state. Didn't know they come with vim-latex because the quickfix window never opens over here when compilation fails.

**Comment by lervag** [comment]
See [latexmk.vim:341](https://github.com/lervag/vim-latex/blob/master/autoload/latex/latexmk.vim#L341),  it shows how the callbacks for opening the quickfix window works. Also note the quickfix options
```
  g:latex_quickfix_autojump
  g:latex_quickfix_ignored_warnings
  g:latex_quickfix_ignore_all_warnings
  g:latex_quickfix_mode
```
In particular, the last option allows to control when the error window should open.

If youo find that this does not work as expected, please open a new issue with a minimal working example.

**Comment by Konfekt** [comment]
Ok. The problem was that by default Terminal vim under Linux is started without a servername (see https://groups.google.com/forum/m/#!topic/vim_use/Jsf4vsmoeXM) . That's why it didn't work out of the box. Now that I supply a servername it works fine.

However, the commands at latexmk.vim:341 do not change the Window title. The proposed settings
```
$compiling_cmd = "xdotool search --name %D set_window --name \"%D compiling...\"";
$success_cmd   = "xdotool search --name %D set_window --name \"%D OK\";";
$failure_cmd   = "xdotool search --name %D set_window --name \"%D FAILURE\";";
```
also rely on different main files for different projects.

**Comment by lervag** [comment]
I'll look into this later. I think we should be able to use the window ID to set the window title, which means it should no longer depend on the main file names.

**Comment by lervag** [comment]
I just pushed some commits; I've begun to prepare for trying to fix some of these issues. As far as I can see, there are actually several issues:
1. Imlement the window title hacks as part of vim-latex and use mupdf_id for robustness
2. Improve robustness of getting and setting mupdf_ids
3. Get page number from mupdf window without reading from title string

**Comment by Konfekt** [comment]
Alright. Regarding 2., over here it works fine for the moment. Cannot explain why. Do you see issues?

**Comment by lervag** [comment]
Not really, no. It seems to work fine. However, I'd like to try to identify the mupdf window that is opened by `latexmk`, so that we don't need to open a new window in addition to the first one.

Regarding the main topic of this issue: It seems I were wrong; the original hack that inspired the functionality here also relied on the window title to parse the page number. Thus I don't really know how to reliably combine the proposed settings to set window titles with the reverse search. That is, I am not able to solve my above number 3.

**Comment by lervag** [comment]
However, I've tried to improve the callback functionality. I'm pushing some changes soon that makes the callback function echo a colorized status to indicate success or fail. This should remove the necessity of the commands proposed in the docs.

**Comment by Konfekt** [comment]
Ah, that's a fine idea to use colors. More expressive than text.

**Comment by lervag** [comment]
Thanks! I'm pushing some more changes soon, in particular one that I am not entirely sure is good: After starting latexmk you added a `sleep` and then some code to get the window ID. I've refactored this so that the window ID getter is only implemented once, and I've moved the window ID getter to the first callback. The only drawback that I can see is that this only works when callbacks are used.

**Comment by lervag** [comment]
I've just pushed some relatively large changes:
1. After latexmk has been started, the first callback will call `latex#view#poststart()`. This function saves the mupdf window ID and returns the focus to the vim window. It also sends keys to MuPDF `g:latex_view_mupdf_send_keys` (default empty string).
2. The same function is also called when MuPDF was opened with `<localleader>lv`.

**Comment by lervag** [comment]
I consider this issue solved. That is, the documentation might require an update, since the trick mentioned is not really that interesting any longer. However, it seems to me that this is not an important update, and I'll leave it as it is for now.

**Comment by Konfekt** [comment]
Regarding callbacks, perhaps a note in the documentation that terminal vim does not use them by default is in place? 

The send keys could be used to open the pdf document where the tex document is at? 

I think the issue about the Window id occurs when you open two vim instances and in each a pdf and close the fistly opened pdf. 

The id of the still open mupdf window is reassigned to that of the first now closed one. May that be?

**Comment by lervag** [comment]
Yes, I think the documentation needs a thorough update. I've opened a new issue for this.

I'm using the send keys to set the zoom level in MuPDF to show the entire page. That is, I send the `H` key. I don't see how the send keys option could be used to open the pdf where the tex document is at, but the callback could definately do that in a similar fashion as the forward search. I'm pushing an update for this soon.

For the last part: I've tested and it seems you are right. It seems that for some reason the order is not always as assumed, that the last reported window ID is the last window opened MuPDF window. However, this seems like a very rare issue, and a simple workaround is to close all pdf windows and open them again.

**Comment by lervag** [comment]
One thing: It seems the window IDs are the same for the same pdf file every time it is opened again. Do you agree? If that is the case, then it seems we shouldn't need to set the window ID if it is already set.

**Comment by lervag** [comment]
At least my last comment seems correct on my end. I pushed a change that utilizes the assumption that a pdf file window ID does not change, so that one only needs to set the mupdf_id once for each session.

**Comment by Konfekt** [comment]
Regarding

> It seems that for some reason the order is not always as assumed, that the last reported window ID is the last window opened MuPDF window. 

I am not sure what `the last window opened MuPDF window` means.

First off, the window id in the last line of the output of `xdotool search --class MuPDF` corresponds to the window last opened. However, if a window that was not opened last is closed, say in the n-th place, then every windows opened afterwards, say at the m-th place, take over the window id of its predecessor, the m-1-st window.

 That was my idea. But just checked again and it seems false. 

Now you say that the window ID is assigned to a PDF file instead? Well, this is false as well.

Open two Vim instances and two different PDFs. Run `xdotool search --class MuPDF`. Then close both and open the second PDF. Then `xdotool search --class MuPDF` show that the ID is that of the first PDF.

**Comment by lervag** [comment]
Interesting. It seems slightly difficult to understand this rule. In any case, the latest version seems to work flawlessly here. Do you manage to produce an ID conflict?

**Comment by Konfekt** [comment]
Well, happened that `:VimLatexView` does not open a window when it was closed, but it's hard to reproduce so far. Before, sometimes two vim instances would forward search to the same mupdf window.

However, sinc then threre have been some changes to vim-latex. So perhaps best to forget about it and come back to it if one can distill a reproducable ID conflict.

**Comment by lervag** [comment]
Yes, I've pushed some updates and changes that should fix the issues you mention. I think we should leave this discussion and issue for now as solved, and reopen (or open a new issue) if we find a problem with the current version.
